version: '3'

services:
  nginx:
    ports:
      - "80:80"
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    links:
      - vue
      - flask
    depends_on:
      - vue
      - flask
    restart: always

  vue:
    ports:
      - "5173"
    build: ./frontend
    restart: always

  flask:
    ports:
      - "5000"
    build: ./backend
    links:
      - mysql
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql:latest
    volumes:
      - ./test.sql:/docker-entrypoint-initdb.d/test.sql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    restart: always
