/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArticleContent: typeof import('./components/ArticleContent.vue')['default']
    ArticleMgr: typeof import('./components/ArticleMgr.vue')['default']
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    FavGrid: typeof import('./components/FavGrid.vue')['default']
    LeftSidePanel: typeof import('./components/LeftSidePanel.vue')['default']
    LoginForm: typeof import('./components/LoginForm.vue')['default']
    ManagePanel: typeof import('./components/ManagePanel.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    PageList: typeof import('./components/PageList.vue')['default']
    RightSidePanel: typeof import('./components/RightSidePanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchTitle: typeof import('./components/SearchTitle.vue')['default']
    UserInfo: typeof import('./components/UserInfo.vue')['default']
    UserMgr: typeof import('./components/UserMgr.vue')['default']
  }
}
